artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  https://github.com/1602saurab/a13_dlops/raw/refs/heads/main/artifacts/data_ingestion/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

  